<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>99106c29-b4fc-4ef3-a040-f047d54c47bd</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.5.3" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="13.5.3" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.5.3" />
    <PackageReference Include="Aspire.Hosting.SqlServer" Version="13.5.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\ApiGateways\YarpApiGateway\YarpApiGateway.csproj" />
    <ProjectReference Include="..\..\..\..\Services\Basket\Basket.API\Basket.API.csproj" />
    <ProjectReference Include="..\..\..\..\Services\Catalog\Catalog.API\Catalog.API.csproj" />
    <ProjectReference Include="..\..\..\..\Services\Discount\Discount.gRPC\Discount.gRPC.csproj" />
    <ProjectReference Include="..\..\..\..\Services\Ordering\Ordering.API\Ordering.API.csproj" />
    <ProjectReference Include="..\..\..\..\WebApps\Shopping.Web\Shopping.Web.csproj" />
  </ItemGroup>

</Project>
